"""add_manual_document_fields

Revision ID: 5b74b1cfcf5c
Revises: 71465cf784f5
Create Date: 2026-04-01 15:29:23.210395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b74b1cfcf5c'
down_revision: Union[str, Sequence[str], None] = '71465cf784f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('verification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('document_photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('ovse_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'ovse_client_id')
    op.drop_column('visit', 'document_photo_path')
    op.drop_column('visit', 'document_type')
    op.drop_column('visit', 'verification_type')
    # ### end Alembic commands ###
