"""add_live_photo_path

Revision ID: 6427425fa461
Revises: 5b74b1cfcf5c
Create Date: 2026-04-01 17:12:58.346742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6427425fa461'
down_revision: Union[str, Sequence[str], None] = '5b74b1cfcf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('live_photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'live_photo_path')
    # ### end Alembic commands ###
