"""add_digilocker_manual_otp_and_photo_fields

Revision ID: ce8826ede6f1
Revises: 6427425fa461
Create Date: 2026-04-02 09:01:07.423949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce8826ede6f1'
down_revision: Union[str, Sequence[str], None] = '6427425fa461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('aadhaar_photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('aadhaar_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('aadhaar_masked', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('pending_otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visit', sa.Column('otp_submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'otp_submitted_at')
    op.drop_column('visit', 'pending_otp')
    op.drop_column('visit', 'aadhaar_masked')
    op.drop_column('visit', 'aadhaar_encrypted')
    op.drop_column('visit', 'aadhaar_photo_path')
    # ### end Alembic commands ###
